### ISSUE TITLE
Déterminer la gouvernance du projet

### ISSUE THREAD

**Issue by rspt** [usine/contribuer.usine.ch#2]
Déterminer la gouvernance du projet ainsi que les relations Usine - Groupe de travail - Contributeur-trice

**Comment by Ianouuu** [comment]
**Gouvernance**

L’Usine (RG) > groupe de travail > communauté Github

L’Usine fonctionne en autogestion. C’est la décisionnaire ultime.

Les décisions collectives de l’Usine sont prise en réunion de gestion (RG) ou assemblée mensuelle (AM) par les usiniens et usiniennes. 

De manière à libérer le temps de discussion et avancer plus vite, la RG détache un groupe de travail (GT) pour réaliser le site Internet.

Le GT dispose d’une certaine marge de manoeuvre pour avancer sur le projet du site mais doit se référer à la RG pour les décisions majeures. 

La RG sera régulièrement sollicitée et consultée pour permettre l’avancement du site et elle pourra revenir à tout moment sur toutes les décisions prises par le GT.

Le groupe de travail du site Internet (GT) est piloté actuellement par rspt et Ianouuu.

**Mise en oeuvre :** 

Pour faciliter l’avancement du projet, le GT a choisi de réaliser le site en open source sur la plateforme Github. 

Les avancements du GT sont consultables en ligne à tout moment afin d’en assurer la transparence. 

Tout le monde peut laisser des commentaires, faire des remarques ou y contribuer directement (ou via mail pour les usiniens et usiniennes).

Ce procédé a été soumis par rspt qui souhaite pouvoir avancer de la façon la plus libre, rapide et transparente tout en offrant la possibilité à tout a chacun d’apporter sa contribution ou remarque au fur et à mesure des avancements.


**Fonctions du GT et répartition des rôles :**

Récolter, rassembler les idées et envies de l’Usine pour le nouveau site Internet auprès de la RG, la permanence, les bureaux des différentes entités  membres de l’Usine etc. (Ianouuu)

Sélectionner, organiser et traduire les idées pour permettre leur réalisation.
(Ianouuu et rspt)

Travailler activement à la réalisation du site tout en modérant la communauté Github. (rspt pour l’aspect technique et Ianouuu pour le général)

Assurer les échanges entre l’Usine et la communauté Github, transmettre les décisions de l’Usine et garantir leur respect. Faire remonter les avancées du projet à l’Usine et la consulter régulièrement pour assurer sa gouvernance. 


**Objectif**

L’objectif du GT est de s’atteler à la réalisation de la « V1 » (version 1), un nouveau site Internet qui sera strictement supérieur au site actuel de l’Usine. 
Cette V1 sera la copie améliorée et remise à jour du site actuel avec des optimisations mineures.
Il est possible que certaines fonctionnalités du site actuel soient tronquée dans la V1 si jugées non pertinentes.
Aucune nouvelle fonctionnalité majeure ne fera partie de cette V1. 
L’objectif est de pouvoir mettre en ligne la V1 le plus vite possible pour remplacer le site Internet actuel.

Tous les projets additionnels pour le site Internet seront repoussés aux versions ultérieures : V2, V3, V4… Ces versions permettront l’implémentation des nouvelles idées et projets de l’Usine pour le site Internet. 
Le GT souhaite repousser les nouvelles idées de fonctionnalités dans les versions ultérieures afin de permettre le déploiement de la V1 dans les plus brefs délais.

**Comment by rspt** [comment]
En me basant sur ce que tu as écris, je proposerais:

# Gouvernance

Un groupe de travail (GT) a été créé par L'Usine afin de gérer le projet du site internet.

Le GT s'occupe des tâches suivantes:
- Mise en place des règles de contribution
- Relation avec les contributeurs-trices
- Relation avec L'Usine
- Gestion du projet du site de L'Usine

Pour toutes questions sensibles ou qui nécessiterais un aval de L'Usine, le GT fait remonter la problématique à L'Usine afin d'aboutir à une décision. L'Usine peut également à tout moment imposer une décision/modification au GT.

Le groupe de travail du site Internet (GT) est piloté actuellement par @rspt et @Ianouuu.
